package domain

import "testing"

func TestPanelValueRoleOf(t *testing.T) {
	cases := []struct {
		name  string
		typ   ActType
		title string
		head  string
		want  PanelValueRole
	}{
		{"extrato de contrato", ActLicitacao, "EXTRATO DO CONTRATO 010/SEMED/2025 DO PREGÃO",
			"EXTRATO DO CONTRATO 010/SEMED/2025 DO PREGÃO\nELETRÔNICO PMSG- 90013/2025.\nProcesso: 7717/2025.\nPartes: MUNICÍPIO DE SÃO GONÇALO e F.P. VIEIRA ENGENHARIA",
			PanelValueContracted},
		{"ratificação de dispensa", ActDispensa, "EXTRATO DE RATIFICAÇÃO DE DISPENSA LICITAÇÃO",
			"EXTRATO DE RATIFICAÇÃO DE DISPENSA LICITAÇÃO\nPROCESSO ADMINSTRATIVO Nº 21577/19\nRATIFICO a situação de dispensa de licitação",
			PanelValueContracted},
		{"adesão a ata", ActContrato, "EXTRATO DE TERMO DE ADESÃO",
			"EXTRATO DE TERMO DE ADESÃO\nPROCESSO ADMINISTRATIVO N.º 6.013/2021\nO MUNICÍPIO DE SÃO GONÇALO, através da Secretaria\nMunicipal de Desenvolvimento Urbano, torna pública a adesão\nà Ata de Registro de Preços n.º 92/2020",
			PanelValueContracted},
		{"contrato de pregão SRP", ActLicitacao, "PREGÃO ELETRÔNICO SRP N.º 035/2021",
			"PREGÃO ELETRÔNICO SRP N.º 035/2021\nCONTRATO N.º 017/FMS/2021.\nPARTES: FUNDAÇÃO MUNICIPAL DE SAÚDE DE SÃO GONÇALO,",
			PanelValueContracted},
		{"ata de registro de preços", ActLicitacao, "EXTRATO DA ATA DE REGISTRO DE PREÇOS",
			"EXTRATO DA ATA DE REGISTRO DE PREÇOS\nO MUNICÍPIO DE SÃO GONÇALO torna público, para o\nconhecimento de todos os interessados, o Extrato da Ata de\nRegistro de Preços Nº 001/SEMMATRAN/2026",
			PanelValueRegistered},
		{"extrato trimestral", ActContrato, "EXTRATO TRIMESTRAL - O MUNICIPIO DE SÃO GONÇALO",
			"EXTRATO TRIMESTRAL - O MUNICIPIO DE SÃO GONÇALO\ntorna público para o conhecimento de todos os interessados,\no Extrato da Trimestral da Ata de Registro de Preços",
			PanelValueRegistered},
		{"homologação no título", ActLicitacao, "EXTRATO DA HOMOLOGAÇÃO DO PREGÃO ELETRÔNICO N°.",
			"EXTRATO DA HOMOLOGAÇÃO DO PREGÃO ELETRÔNICO N°.\n90013/2025.\nPROCESSO ADMINISTRATIVO Nº. 7717/2025.\nNos termos do relatório final apresentado pelo Pregoeiro",
			PanelValueNone},
		{"homologação só no texto", ActLicitacao, "PREGÃO ELETRÔNICO Nº 90030/2025",
			"PREGÃO ELETRÔNICO Nº 90030/2025\nPROCESSO ADMINISTRATIVO Nº 2.686/2025\nHomologo o resultado da licitação referente ao Pregão Eletrônico nº\n90030/2025",
			PanelValueNone},
		{"aviso de licitação", ActLicitacao, "AVISO DE LICITAÇÃO",
			"AVISO DE LICITAÇÃO\nPregão Presencial FMS SRP nº 009/2016.\nProcesso nº 2.888/2016.",
			PanelValueNone},
		{"publicação trimestral de ata", ActContrato, "EXTRATO DE PUBLICAÇÃO TRIMESTRAL O MUNICIPIO DE",
			"EXTRATO DE PUBLICAÇÃO TRIMESTRAL O MUNICIPIO DE\nSÃO GONÇALO, torna público para o conhecimento de todos\nos interessados, o Extrato da Ata de Registro de Preços",
			PanelValueRegistered},
		{"extrato de publicação de contrato", ActContrato, "EXTRATO DE PUBLICAÇÃO DE CONTRATO",
			"EXTRATO DE PUBLICAÇÃO DE CONTRATO Processo nº17322/2010, Contrato nº 01/2010",
			PanelValueContracted},
		{"multa", ActContrato, "EXTRATO DE MULTA",
			"EXTRATO DE MULTA\nO PREFEITO DO MUNICÍPIO DE SÃO GONÇALO, no\nuso de suas atribuições legais, decide aplicar a sanção de\nmulta à empresa Allianza Infraestrutura do Brasil S.A.",
			PanelValueNone},
		{"cancelamento de empenho", ActContrato, "EXTRATO DE CANCELAMENTO DE NOTA DE EMPENHO",
			"EXTRATO DE CANCELAMENTO DE NOTA DE EMPENHO\nPROCEDIMENTO ADMINISTRATIVO N.º 1104/2020",
			PanelValueNone},
		{"sanção", ActContrato, "EXTRATO DE SANÇÃO", "EXTRATO DE SANÇÃO O INSTITUTO DE PREVIDÊNCIA DO MUNICÍPIO", PanelValueNone},
		{"notificação", ActContrato, "EXTRATO DE NOTIFICAÇÃO", "EXTRATO DE NOTIFICAÇÃO Notificação 04/2014. A SECRETARIA MUNICIPAL", PanelValueNone},
		{"aditivo", ActAditivo, "EXTRATO DO PRIMEIRO TERMO ADITIVO AO CONTRATO 010/SEMED/2025",
			"EXTRATO DO PRIMEIRO TERMO ADITIVO AO CONTRATO 010/SEMED/2025 DO PREGÃO ELETRÔNICO PMSG-90013/2025. Processo: 7.717/2025.",
			PanelValueAmended},
		{"aditivo com título de contrato", ActContrato, "CONTRATO N° 005/2019",
			"CONTRATO N° 005/2019 PARTES: SECRETARIA MUNICIPAL DE SAÚDE E DEFESA CIVIL e SOBRAL LABORATÓRIOS DE ANÁLISES CLÍNICAS LTDA. OBJETO: O presente termo aditivo tem por objeto a prorrogação do contrato n° 005/2019",
			PanelValueAmended},
		{"prorrogação com título de pregão", ActLicitacao, "PREGÃO ELETRÔNICO N° 016/2022",
			"PREGÃO ELETRÔNICO N° 016/2022 PARTES: FUNDAÇÃO MUNICIPAL DE SAÚDE DE SÃO GONÇALO E A4PM ANALYTICS FOR PUBLIC MANAGEMENT LTDA. OBJETO: TERMO ADITIVO PARA PRORROGAR O PRAZO CONTRATUAL",
			PanelValueAmended},
		{"prorrogação sem a palavra aditivo", ActContrato, "CONTRATO Nº 013/2019",
			"CONTRATO Nº 013/2019 PARTES: MUNICÍPIO DE SÃO GONÇALO e OFTALMOCLÍNICA SÃO GONÇALO LTDA OBJETO: O presente tem por objeto prorrogar a vigência do contrato n°. 013/2019",
			PanelValueAmended},
		{"termo de prorrogação", ActContrato, "EXTRATO DO 2º (SEGUNDO) TERMO DE PRORROGAÇÃO DE CONTRATO",
			"EXTRATO DO 2º (SEGUNDO) TERMO DE PRORROGAÇÃO DE CONTRATO CHAMADA PÚBLICA N.º 001/2013", PanelValueAmended},
		{"prorrogação de ata", ActLicitacao, "EXTRATO DE PRORROGAÇÃO DA ATA DE REGISTRO DE PREÇOS.",
			"EXTRATO DE PRORROGAÇÃO DA ATA DE REGISTRO DE PREÇOS. O MUNICÍPIO DE SÃO GONÇALO torna público o Extrato de Prorrogação da ATA DE REGISTRO DE PREÇOS Nº 002/SEMED/2025",
			PanelValueAmended},
		{"rerratificação", ActDispensa, "EXTRATO DE RERRATIFICAÇÃO DE CONTRATO N.º 008/2022",
			"EXTRATO DE RERRATIFICAÇÃO DE CONTRATO N.º 008/2022 PROCEDIMENTO ADMINISTRATIVO N.º 3090/2021", PanelValueNone},
		{"retificação com onde se lê", ActContrato, "TERMO DE RERRATIFICAÇÃO AO CONTRATO",
			"AO CONTRATO Nº 001/2025. Onde se lê: “VALOR ESTIMADO: R$ 6.896.855,64", PanelValueNone},
		{"homologação no meio do texto", ActLicitacao, "PREGÃO ELETRÔNICO N° 37/2022",
			"PREGÃO ELETRÔNICO N° 37/2022 PROCESSO Nº 1.234/2022 O PRESIDENTE DA FUNDAÇÃO, HOMOLOGANDO vencedora a proposta no valor de R$ 14.376.384,00",
			PanelValueNone},
		{"reajuste de aluguel", ActContrato, "EXTRATO DE REAJUSTE DE VALOR MENSAL DE CONTRATO",
			"EXTRATO DE REAJUSTE DE VALOR MENSAL DE CONTRATO DE LOCAÇÃO PROCEDIMENTO ADMINISTRATIVO Nº 28.909/14", PanelValueNone},
		{"ata prorrogada", ActAta, "ATA DE REGISTRO DE PREÇOS Nº 02/FMS/2024.",
			"ATA DE REGISTRO DE PREÇOS Nº 02/FMS/2024. VALOR GLOBAL DO CONTRATO: R$ 1.029.745,32, o qual correrá à conta da dotação orçamentária. PRAZO: Fica prorrogado por 12 (doze) meses o prazo",
			PanelValueAmended},
		{"homologação revisada", ActLicitacao, "PREGÃO ELETRÔNICO - PMSG N.º 057/2020",
			"PREGÃO ELETRÔNICO - PMSG N.º 057/2020 PROCESSO ADMINISTRATIVO N.º 18.171/2020 – PMSG Fica a homologação do Pregão Eletrônico", PanelValueNone},
		{"homologo a licitação", ActLicitacao, "PREGÃO ELETRÔNICO Nº 046/2012",
			"PREGÃO ELETRÔNICO Nº 046/2012 PROCESSO Nº 9.284/2012. OBJETO: medalhas e troféus. Homologo a licitação relativa ao objeto em epígrafe", PanelValueNone},
		{"corrigenda com leia-se", ActDispensa, "DISPENSA DE LICITAÇÃO N.º 90005/2024",
			"DISPENSA DE LICITAÇÃO N.º 90005/2024 PROCESSO ADMINISTRATIVO N.º 24.501/2024 (...) no valor total de R$ 14.440,00 (...)” Leia-se: “TERMO DE ADJUDICAÇÃO", PanelValueNone},
		{"contrato que cita a homologação continua contratado", ActContrato, "EXTRATO DE CONTRATO",
			"EXTRATO DE CONTRATO Nº 010/2022 PARTES: MUNICÍPIO DE SÃO GONÇALO e EMPRESA X LTDA, decorrente da homologação do Pregão Eletrônico nº 12/2022",
			PanelValueContracted},
		{"ata de reunião de conselho", ActAta, "ATA DA REUNIÃO ORDINÁRIA Nº 03/2024 DO CONSELHO",
			"ATA DA REUNIÃO ORDINÁRIA Nº 03/2024 DO CONSELHO MUNICIPAL DE ASSISTÊNCIA SOCIAL DE SÃO GONÇALO – CMAS/SG", PanelValueNone},
		{"ata de assembleia", ActAta, "ATA DA ASSEMBLÉIA GERAL ORDINÁRIA (AGO) 25/11/2024 DO CONSEL",
			"ATA DA ASSEMBLÉIA GERAL ORDINÁRIA (AGO) 25/11/2024 DO CONSELHO MUNICIPAL DE DEFESA DOS DIREITOS", PanelValueNone},
		{"extrato de ata com número antes de registro", ActContrato, "EXTRATO",
			"EXTRATO DE ATA 024/SEMDUR/2021 DE REGISTRO DE PREÇOS N.º O MUNICÍPIO DE SÃO GONÇALO torna público", PanelValueRegistered},
		{"corrigenda de ata", ActLicitacao, "EXTRATO DE CORRIGENDA DE ATA DE REGISTRO DE PREÇOS Nº 002/SEMDUR/2023",
			"EXTRATO DE CORRIGENDA DE ATA DE REGISTRO DE PREÇOS Nº 002/SEMDUR/2023 O MUNICÍPIO DE SÃO GONÇALO torna público", PanelValueNone},
		{"designação de fiscais", ActLicitacao, "PREGÃO ELETRÔNICO Nº 001/2014",
			"PREGÃO ELETRÔNICO Nº 001/2014 Designação dos servidores Marcelo Costa de Oliveira, matrícula nº 21.627, para exercer a fiscalização do contrato oriundo da licitação supracitada",
			PanelValueNone},
		{"revogação", ActLicitacao, "EXTRATO DE REVOGAÇÃO DO PREGÃO ELETRÔNICO PMSG N° 004/2023.",
			"EXTRATO DE REVOGAÇÃO DO PREGÃO ELETRÔNICO PMSG N° 004/2023. Processo: 3.199/2023", PanelValueNone},
		{"readequação de ata", ActContrato, "EXTRATO DE READEQUAÇÃO DA ATA DE REGISTRO DE PREÇOS",
			"EXTRATO DE READEQUAÇÃO DA ATA DE REGISTRO DE PREÇOS PROCESSO ADMINISTRATIVO Nº 560/2016.", PanelValueNone},
		{"edital de chamamento", ActLicitacao, "EDITAL DE CHAMAMENTO PÚBLICO",
			"EDITAL DE CHAMAMENTO PÚBLICO CHAMADA PÚBLICA Nº. 001/2024/FMS/SG Objeto: O presente edital de chamamento público tem por objeto a seleção",
			PanelValueNone},
		{"preâmbulo de chamamento", ActLicitacao, "CHAMAMENTO PÚBLICO CP - Nº 001/SMTC/2026",
			"CHAMAMENTO PÚBLICO CP - Nº 001/SMTC/2026 1. PREÂMBULO 1.1. O MUNICÍPIO DE SÃO GONÇALO, por meio da Secretaria", PanelValueNone},
		{"publicação de chamamento", ActLicitacao, "CHAMAMENTO PÚBLICO PARA CELEBRAÇÃO DE PARCERIA",
			"CHAMAMENTO PÚBLICO PARA CELEBRAÇÃO DE PARCERIA COM ORGANIZAÇÃO DA SOCIEDADE CIVIL. Publicação do Chamamento Público: nº 00", PanelValueNone},
		{"termo de permissão de uso", ActContrato, "TERMO DE PERMISSÃO DE USO",
			"TERMO DE PERMISSÃO DE USO TERMO DE PERMISSÃO DE USO SITUADO À RUA DO IMÓVEL Nº. NO MUNICÍPIO DE SÃO GONÇALO", PanelValueNone},
		{"homologação depois dos 400 caracteres", ActLicitacao, "PREGÃO ELETRÔNICO SRP PMSG Nº 90015/2025.",
			"PREGÃO ELETRÔNICO SRP PMSG Nº 90015/2025. Processo Administrativo n.°7461/2025 Nos termos apresentados no processo n.º 7461/2025, referente ao Pregão Eletrônico nº 900152025 SRP, cujo objeto é o registro de preços para futura e eventual contratação de empresa especializada no fornecimento de material de limpeza, higienização e descartáveis necessários para atendimento da Administração Direta da Prefeitura Municipal de São Gonçalo, ADJUDICO E HOMOLOGO o resultado da presente Licitação",
			PanelValueNone},
		{"aditivo de outro ato colado depois dos 400 caracteres não conta", ActContrato, "EXTRATO DE CONTRATO",
			"EXTRATO DE CONTRATO Nº 010/2022 PARTES: MUNICÍPIO DE SÃO GONÇALO e EMPRESA X LTDA. OBJETO: prestação de serviços de limpeza urbana em todo o município, com fornecimento de mão de obra, materiais e equipamentos, conforme termo de referência e proposta da contratada, que integram este instrumento independentemente de transcrição, pelo prazo de doze meses contados da ordem de início dos serviços, com valor global de R$ 1.000.000,00 (um milhão de reais). São Gonçalo, 10 de março de 2022. EXTRATO DO PRIMEIRO TERMO ADITIVO AO CONTRATO",
			PanelValueContracted},
		{"homologação de dispensa continua contratada", ActDispensa, "RATIFICAÇÃO DE DISPENSA DE LICITAÇÃO",
			"RATIFICAÇÃO DE DISPENSA DE LICITAÇÃO Processo Administrativo nº 4.608/14. Com base no parecer favorável da Secretaria Municipal de Controle Interno, HOMOLOGO a dispensa de licitação, nos termos do Inciso II do artigo 24 da Lei Federal nº 8.666/1993, no valor de R$ 4.860,00",
			PanelValueContracted},
		{"homologação de inexigibilidade com tipo licitação continua contratada", ActLicitacao, "INEXIGIBILIDADE DE LICITAÇÃO",
			"INEXIGIBILIDADE DE LICITAÇÃO Processo Administrativo n.º 19.967/2024 RATIFICO e HOMOLOGO a situação de inexigibilidade de licitação", PanelValueContracted},
		{"contrato prorrogável continua contratado", ActContrato, "EXTRATO DE CONTRATO",
			"EXTRATO DE CONTRATO Nº 010/2022 PARTES: MUNICÍPIO DE SÃO GONÇALO e EMPRESA X LTDA. OBJETO: prestação de serviços de limpeza. PRAZO: 12 meses, prorrogável na forma da lei",
			PanelValueContracted},
	}
	for _, c := range cases {
		if got := PanelValueRoleOf(c.typ, c.title, c.head); got != c.want {
			t.Errorf("%s: veio %d, esperava %d", c.name, got, c.want)
		}
	}
}

func TestAmendmentValueCents(t *testing.T) {
	cases := []struct {
		name            string
		head            string
		mainValue       int64
		declaredBP      int
		contractedCents int64
		want            int64
	}{
		{"prorrogação vale o valor do novo período",
			"PREGÃO ELETRÔNICO N° 016/2022 PARTES: FUNDAÇÃO MUNICIPAL DE SAÚDE E A4PM ANALYTICS FOR PUBLIC MANAGEMENT LTDA. OBJETO: TERMO ADITIVO PARA PRORROGAR O PRAZO CONTRATUAL PELO PERÍODO DE 12 (DOZE) MESES. VALOR TOTAL DO CONTRATO: R$ 10.439.280,00",
			1043928000, 0, 1043928000, 1043928000},
		{"prorrogação sem ônus não soma",
			"EXTRATO DO SEGUNDO TERMO ADITIVO AO CONTRATO Nº 012/SEMDUR/2021. OBJETO: prorrogação do prazo de execução da obra por 180 dias, sem ônus para a Administração. VALOR GLOBAL: R$ 2.500.000,00",
			250000000, 0, 250000000, 0},
		{"prorrogação sem alteração de valor não soma",
			"TERMO ADITIVO. OBJETO: prorrogação do prazo de vigência, sem alteração do valor contratual. Valor total: R$ 800.000,00",
			80000000, 0, 80000000, 0},
		{"acréscimo em reais vence o novo total",
			"EXTRATO DO PRIMEIRO TERMO ADITIVO AO CONTRATO Nº 007/2015. OBJETO: acréscimo de R$ 150.000,00 ao valor contratado, passando o valor global a R$ 650.000,00",
			65000000, 0, 50000000, 15000000},
		{"percentual declarado sobre o contratado",
			"EXTRATO DO PRIMEIRO TERMO ADITIVO AO CONTRATO FMS Nº 007/2015. OBJETO: acréscimo quantitativo equivalente a 20% do valor contratado. Valor global: R$ 1.200.000,00",
			120000000, 2000, 100000000, 20000000},
		{"aditivo de acréscimo sem percentual nem valor de acréscimo fica sem valor",
			"EXTRATO DO TERCEIRO TERMO ADITIVO AO CONTRATO Nº 003/2024. OBJETO: alteração quantitativa. VALOR GLOBAL: R$ 62.860.061,00",
			6286006100, 0, 0, 0},
		{"supressão fica sem valor",
			"Primeiro Termo Aditivo (Supressão de Valor) ao Contrato PMSG n° 006/15. VALOR: R$ 8.548.741,00",
			854874100, 0, 900000000, 0},
		{"acréscimo financeiro em reais",
			"TERCEIRO TERMO ADITIVO AO CONTRATO PMSG nº 001/2023. OBJETO: 1) O presente termo Aditivo tem por objetivo o acréscimo financeiro de R$ 2.599.248,86 (dois milhões, quinhentos e noventa e nove mil, duzentos e quarenta e oito reais e oitenta e seis centavos) que equivale a aproximadamente 5,11% do valor inicial do contrato. 2) O prazo de vigência do referido contrato fica prorrogado por mais 03 (três) meses. O valor global do contrato passará a ser de R$ 53.514.722,03",
			5351472203, 511, 5091547317, 259924886},
		{"acréscimo financeiro equivalente a",
			"PRIMEIRO TERMO ADITIVO AO CONTRATO PMSG nº 008/2022. OBJETO: O presente termo Aditivo tem por objetivo o acréscimo financeiro equivalente a R$ 6.383.856,64 (seis milhões, trezentos e oitenta e três mil, oitocentos e cinquenta e seis reais e sessenta e quatro centavos) do valor inicial do contrato e prorrogação de prazo por mais 06 (seis) meses",
			4886986196, 0, 4248600532, 638385664},
		{"valor global que permanece não soma",
			"SEGUNDO TERMO ADITIVO AO CONTRATO PMSG Nº 001/2023. OBJETO: O presente termo Aditivo tem por objetivo a prorrogação do prazo de vigência do contrato PMSG nº 001/2023 por mais 03 (três) meses. VALOR GLOBAL DO CONTRATO CONSIDERANDO O 2º TERMO ADITIVO: O valor global do contrato permanece em R$ 50.915.473,17",
			5091547317, 0, 5091547317, 0},
		{"prorrogação de menos de doze meses repete o valor global",
			"QUARTO TERMO ADITIVO DE PRORROGAÇÃO DE PRAZO AO CONTRATO N.º 001/2023. VALOR GLOBAL DO CONTRATO: R$ 53.514.722,03 (cinquenta e três milhões). PRAZO: Fica o contrato PMSG nº 001/SEMDUR/2023 prorrogado por mais 02 (dois) meses, com término para 12/10/2024.",
			5351472203, 0, 5091547317, 0},
		{"prorrogação de vigência e execução de obra repete o valor global",
			"Objeto: prorrogação de prazo. Valor global do contrato: R$ 5.987.504,40 (cinco milhões); Prazo de vigência do contrato: prorrogado por mais 6 (seis) meses de vigência e 4 (quatro) meses de execução a contar de 15/08/2024",
			598750440, 0, 598750440, 0},
		{"prorrogação de doze meses de serviço contínuo vale o valor do período",
			"EXTRATO DO PRIMEIRO TERMO ADITIVO AO CONTRATO 010/SEMED/2025. Objeto: Prorrogação do prazo por 12 (doze) meses da contratação de serviços de engenharia de manutenção preventiva e corretiva predial. Valor Mensal: R$ 9.252.146,97. Valor Total: R$ 111.025.763,58",
			11102576358, 0, 11102576358, 11102576358},
	}
	for _, c := range cases {
		if got := AmendmentValueCents(c.head, c.mainValue, c.declaredBP, c.contractedCents); got != c.want {
			t.Errorf("%s: esperava %d, veio %d", c.name, c.want, got)
		}
	}
}
