name: carga-federal

on:
  schedule:
    - cron: "0 11 * * 0"
  workflow_dispatch:

concurrency:
  group: carga-federal

jobs:
  carga:
    uses: ./.github/workflows/_carga.yml
    with:
      cmd: federal
      args: ""
      timeout: 30
    secrets: inherit
