name: carga-sancoes

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

concurrency:
  group: carga-sancoes

jobs:
  carga:
    uses: ./.github/workflows/_carga.yml
    with:
      cmd: sancoes
      args: ""
      timeout: 30
    secrets: inherit
